cp imports/wg3_blob.cpp ../../WonderGUI/src/base/wg_blob.cpp							
cp imports/wg3_blob.h ../../WonderGUI/src/base/wg_blob.h							
cp imports/wg3_color.cpp ../../WonderGUI/src/base/wg_color.cpp						
cp imports/wg3_color.h ../../WonderGUI/src/base/wg_color.h							
cp imports/wg3_enumextras.cpp ../../WonderGUI/src/base/wg_enumextras.cpp
cp imports/wg3_enumextras.h ../../WonderGUI/src/base/wg_enumextras.h							
cp imports/wg3_geo.cpp ../../WonderGUI/src/base/wg_geo.cpp							
cp imports/wg3_geo.h ../../WonderGUI/src/base/wg_geo.h							
cp imports/wg3_gfxdevice.cpp ../../WonderGUI/src/base/wg_gfxdevice.cpp					
cp imports/wg3_gfxdevice.h ../../WonderGUI/src/base/wg_gfxdevice.h						
cp imports/wg3_interface.cpp ../../WonderGUI/src/interfaces/wg_interface.cpp				
cp imports/wg3_interface.h ../../WonderGUI/src/interfaces/wg_interface.h				
cp imports/wg3_nullgfxdevice.cpp ../../WonderGUI/src/base/wg_nullgfxdevice.cpp				
cp imports/wg3_nullgfxdevice.h ../../WonderGUI/src/base/wg_nullgfxdevice.h					
cp imports/wg3_object.cpp ../../WonderGUI/src/base/wg_object.cpp						
cp imports/wg3_object.h ../../WonderGUI/src/base/wg_object.h							
cp imports/wg3_pointers.h ../../WonderGUI/src/base/wg_pointers.h						
cp imports/wg3_stronginterfaceptr.h ../../WonderGUI/src/base/wg_stronginterfaceptr.h 			
cp imports/wg3_strongptr.h ../../WonderGUI/src/base/wg_strongptr.h						
cp imports/wg3_surface.cpp ../../WonderGUI/src/base/wg_surface.cpp						
cp imports/wg3_surface.h ../../WonderGUI/src/base/wg_surface.h						
cp imports/wg3_surfacefactory.cpp ../../WonderGUI/src/base/wg_surfacefactory.cpp				
cp imports/wg3_surfacefactory.h	../../WonderGUI/src/base/wg_surfacefactory.h					
cp imports/wg3_types.h ../../WonderGUI/src/base/wg_types.h							
cp imports/wg3_util.cpp ../../WonderGUI/src/base/wg_util.cpp							
cp imports/wg3_util.h ../../WonderGUI/src/base/wg_util.h							
cp imports/wg3_weakinterfaceptr.h ../../WonderGUI/src/base/wg_weakinterfaceptr.h				
cp imports/wg3_weakptr.h ../../WonderGUI/src/base/wg_weakptr.h						
cp imports/wondergui.h ../../WonderGUI/src/wondergui.h								
cp imports/opengl/wg3_glgfxdevice.cpp ../../WonderGUI/src/gfxdevices/opengl/wg_glgfxdevice.cpp			
cp imports/opengl/wg3_glgfxdevice.h ../../WonderGUI/src/gfxdevices/opengl/wg_glgfxdevice.h			
cp imports/opengl/wg3_glsurface.cpp ../../WonderGUI/src/gfxdevices/opengl/wg_glsurface.cpp			
cp imports/opengl/wg3_glsurface.h ../../WonderGUI/src/gfxdevices/opengl/wg_glsurface.h				
cp imports/opengl/wg3_glsurfacefactory.cpp ../../WonderGUI/src/gfxdevices/opengl/wg_glsurfacefactory.cpp	
cp imports/opengl/wg3_glsurfacefactory.h ../../WonderGUI/src/gfxdevices/opengl/wg_glsurfacefactory.h		
cp imports/wg_soft/wg3_softgfxdevice.cpp ../../WonderGUI/src/gfxdevices/software/wg_softgfxdevice.cpp		
cp imports/wg_soft/wg3_softgfxdevice.h ../../WonderGUI/src/gfxdevices/software/wg_softgfxdevice.h		
cp imports/wg_soft/wg3_softsurface.cpp ../../WonderGUI/src/gfxdevices/software/wg_softsurface.cpp		
cp imports/wg_soft/wg3_softsurface.h ../../WonderGUI/src/gfxdevices/software/wg_softsurface.h			
cp imports/wg_soft/wg3_softsurfacefactory.cpp ../../WonderGUI/src/gfxdevices/software/wg_softsurfacefactory.cpp
cp imports/wg_soft/wg3_softsurfacefactory.h ../../WonderGUI/src/gfxdevices/software/wg_softsurfacefactory.h	